DELIMITER //
DROP TRIGGER IF EXISTS CHECK_TRANSACTION_TYPE //
CREATE TRIGGER CHECK_TRANSACTION_TYPE BEFORE INSERT ON BANK_TRANSACTION
FOR EACH ROW
BEGIN
    DECLARE MSG VARCHAR(128);
    IF NEW.TYPE NOT IN ('W','D') THEN
        SET MSG = CONCAT('TXN TYPE ERROR: iNVALID TYPE: ', CAST(NEW.TYPE AS CHAR));
        SIGNAL SQLSTATE '45002' SET MESSAGE_TEXT = MSG;
    END IF;
END
//

DELIMITER ;