DELIMITER //
DROP TRIGGER IF EXISTS TNX_SYNC //
CREATE TRIGGER TNX_SYNC BEFORE INSERT ON BANK_TRANSACTION
FOR EACH ROW
BEGIN
    DECLARE MSG VARCHAR(128);
    IF NEW.TYPE LIKE 'W' THEN
        UPDATE BANK_MASTER
        SET BALANCE=(BALANCE-NEW.AMOUNT)
        WHERE NAME=NEW.NAME;
    END IF;
    
     IF NEW.TYPE LIKE 'D' THEN
        UPDATE BANK_MASTER
        SET BALANCE=(BALANCE+NEW.AMOUNT)
        WHERE NAME=NEW.NAME;
    END IF;
END
//

DELIMITER ;
