/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sarvesh' at '12/7/18 1:37 PM' with Gradle 3.0
 *
 * @author Sarvesh, @date 12/7/18 1:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
