/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sarvesh' at '4/7/18 2:56 PM' with Gradle 3.0
 *
 * @author Sarvesh, @date 4/7/18 2:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
