CREATE TABLE `BANK_MASTER`(`NAME` VARCHAR(70) NOT NULL PRIMARY KEY, `BALANCE` FLOAT);
CREATE TABLE `BANK_TRANSACTION`(`NAME` VARCHAR(70) NOT NULL, `AMOUNT` FLOAT, `TYPE` CHAR(1), `DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT FK_PersonOrder FOREIGN KEY (`NAME`) REFERENCES `BANK_MASTER`(`NAME`));
