DELIMITER //
DROP TRIGGER IF EXISTS CHECK_UPDATE_BALANCE //
CREATE TRIGGER CHECK_UPDATE_BALANCE BEFORE UPDATE ON CUSTOMER
FOR EACH ROW
BEGIN
    DECLARE MSG VARCHAR(128);
    IF NEW.AMOUNT < 1000 THEN
        SET MSG = CONCAT('BALANCE ERROR: Trying to insert a insufficient value in bank: ', CAST(NEW.AMOUNT AS CHAR));
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG;
    END IF;
END
//

DELIMITER ;