/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sarvesh' at '15/7/18 7:33 PM' with Gradle 3.0
 *
 * @author Sarvesh, @date 15/7/18 7:33 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
