/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sarvesh' at '6/7/18 10:18 AM' with Gradle 3.0
 *
 * @author Sarvesh, @date 6/7/18 10:18 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
