/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sarvesh' at '14/7/18 11:44 AM' with Gradle 3.0
 *
 * @author Sarvesh, @date 14/7/18 11:44 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
