--DEPARTMENT WISE JOBWISE SUM OF SALARY OF EMPLOYEES WHOSE SUM OF SALARY SHOULD BE GREATER THAN 2000 
--AND DISPLAY IN ORDER OF SUM OF SALARY


SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT E.JOB,D.DNAME,SUM(E.SAL)  AS SALARY
FROM EMP E JOIN 
DEPT D
ON E.DEPTNO=D.DEPTNO
GROUP BY DNAME,JOB
HAVING SUM(E.SAL)>2000
ORDER BY SUM(E.SAL) desc